### ISSUE TITLE
Verify signatures on messages

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#135]
Right now we are not verifying signatures on messages before displaying them. 

https://github.com/ZbayApp/monorepo/pull/29#discussion_r780182831

We should do this, and tests should confirm that we are. 

We've discussed verifying this in the orbitdb layer so that if pubkey and signature don't match a message is never added to orbitdb by any peer.

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/154

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/159

**Comment by kingalg** [comment]
@siepra is there any way to check it manually or should I belive you and move it to "done"?
