### ISSUE TITLE
Update Quiet logo

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#145]
hw will provide this.

**Comment by holmesworcester** [comment]
Let's use a blank region of black now, as a placeholder just to move this through. 

I owe everyone a cute logo.

**Comment by kingalg** [comment]
In 0.3.0-alpha.7 I was able to find old zbay logo in one place on Windows but in 0.3.0-aplha.8 it's fixed. Everywhere I checked I can see black square so I consider this task done.
