### ISSUE TITLE
Allow hyphen in channel name validation regex patern

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#169]

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/197

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

It's working.

![Screenshot 2022-03-16 at 12 27 20](https://user-images.githubusercontent.com/68909168/158579976-517a7acb-d835-44ff-bc5c-14fd0e87d1e0.png)
