### ISSUE TITLE
User should be able to see which channels have new, unread messages

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#170]
Right now you can't see when you receive new messages on a channel that you have not joined. 

Previously we bolded the channel name when there was an unread message, and unbolded once you switched to it. 

We should restore that functionality. Styles for channels with unread messages are here:

https://www.figma.com/file/UAK1sz35A3glgS2T2tWUxJ/Sidebar---Unread-messages%2C-mentions%2C-badges?node-id=11%3A421

Note there is also a hover style for channels.

While we're doing this, let's add that hover style as well.

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

Right now we don't have "joining channels" logic and it will be implemented from the scratch once we decide on this so I'm closing this task.
