### ISSUE TITLE
Nectar-Waggle websocket connection closes on device sleep and never starts again

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#172]
It's caused by the mechanism for restoring the connection on app-reload. 
After reloading, the connection is being restored by it turns out that awakening device does not fire the proper event

Sources:

`frontend/src/renderer/index.ts`

`ipcRenderer.send('start-waggle')`

```
ipcRenderer.on('waggleInitialized', (_event) => {
  log('waggle initialized')
  store.dispatch(waggleHandlers.actions.setIsWaggleConnected(true))
})
```
Previously reported here: https://github.com/ZbayApp/zbay/issues/755

**Comment by vinkabuki** [comment]
https://www.electronjs.org/docs/latest/api/power-monitor

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/191

**Comment by siepra** [comment]
https://github.com/ZbayApp/zbay/issues/755

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

Fixed.
