### ISSUE TITLE
Incorrect error message when user creating channel with duplicate name

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#180]
steps to reproduce:

1. create channel named "test"
2. create another channel named "test"

expected: app lets you create two similarly named channels OR app blocks you with an error message such as "Channel name taken"

I think we have to do the latter for now because we need unique naming for the channel key (which is broken, but there's an issue for this)

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/197

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3
App behave as expected: Channel with this name already exists

![Screenshot 2022-03-15 at 13 31 45](https://user-images.githubusercontent.com/68909168/158378211-fb04b7fb-5afb-46de-bb6d-507d7cb3bd38.png)
