### ISSUE TITLE
'An update is available for Zbay' - note in updater screen (Quiet)

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#187]

**Comment by vinkabuki** [comment]
https://github.com/ZbayApp/monorepo/pull/194

**Comment by kingalg** [comment]
Can't check it on version 0.3.0-alpha.8 because automatic update is disabled. Bartek will enable it for with the next update. I'm going to check this then.

**Comment by kingalg** [comment]
Not possible to check in this version (0.4.0-alpha.3) as well, so I'm waiting for the next one.

**Comment by holmesworcester** [comment]
Okay, let's leave this here then.

**Comment by kingalg** [comment]
Version: 0.4.6-alpha.0

Fixed.
