### ISSUE TITLE
Clicking on "x" in Search for Channels input results in error

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#207]
Clicking on inner 'x' (the one inside input) results in error:

![image](https://user-images.githubusercontent.com/6099829/152809142-a23b22b0-a6e5-4846-8593-4d39a01a07a6.png)

![image](https://user-images.githubusercontent.com/6099829/152808901-3c1c68b0-da81-4026-b65e-834392dba68a.png)

**Comment by siepra** [comment]
It's more complex problem. We should use react-hook-form instead of Formik in this component.
This feature is Private Channels related
