### ISSUE TITLE
UI breaks below 312px width

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#21]

**Comment by siepra** [comment]
<img width="880" alt="Zrzut ekranu 2021-12-27 o 09 09 04" src="https://user-images.githubusercontent.com/15381135/147450159-da0757e3-1ddc-430c-9c33-2f7e67c20563.png">

**Comment by holmesworcester** [comment]
we can limit the min window size.

**Comment by vinkabuki** [comment]
I don't think this is issue at all, windows size is limited - and UI breaks only if you open developer tools and stretch it
