### ISSUE TITLE
User sees registration modal after restarting the app

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#222]
How to reproduce:
* create new community, register and close the app right after seeing general channel
* reopen the app - "register a username" modal is visible

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/264

Fix for forcing saving data to file is attached to window's 'close; event.
However testcafe electron plugin doesn't actually closes the window between tests so this event is not called - therefore we can't have an automatic test for this case at the moment.

**Comment by kingalg** [comment]
Can't check it on version 0.3.0-alpha.8 because automatic update is disabled. Bartek will enable it for with the next update. I'm going to check this then.
