### ISSUE TITLE
Multiple "simultaneous" messages break orbitdb, or channel

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#232]
This is the issue we identified in orbitdb and built the test PR for. 

We should just go and start fixing this, and ask anders how to as we go.

**Comment by holmesworcester** [comment]
We decided we'd use the branch that has the fix and try it, if they're slow to merge

**Comment by holmesworcester** [comment]
So we'll update orbitdb and try it out.

**Comment by EmiM** [comment]
How to reproduce the problem: https://docs.google.com/document/d/1DceQJSgqyUcTcQpaIG-B0p1xU4gRawxBVKkyjdbtqx8/edit

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/281

**Comment by kingalg** [comment]
I wasn't able to break the app this way in version 0.3.0-alpha.8 so I'm going to say that it's fixed. It will still be part of standard QA before releasing each new version.
