### ISSUE TITLE
User gets incorrect "username already taken" error due to request timeout

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#238]
What happens: sometimes a user registers and they get a "username already taken" error when the username is not taken.

We think this happens because we are timing out registration requests and retrying because sometimes Tor takes forever. This actually worked to make it faster and more reliable. 

HOWEVER. Sometimes when the request times out the registration request has already been received. So when it retries, the username is already taken. 

One proposed solution is to not time out requests and instead open multiple requests and leave them open indefinitely. 

This would still cause the error to happen in some cases if the connection was interrupted for some other reason before the username registration was received by the user. 

Another option, probably a better one, is to not register the username until the user *responds* to the response, and to have some retry. Let's think this through and get it solid.

And let's make test cases for interrupting the connection during registration at the worst times and ensuring things work correctly.

**Comment by siepra** [comment]
The timeout seems not to be a problem itself.
`  public sendCertificateRegistrationRequest = async (
    serviceAddress: string,
    userCsr: string,
    requestTimeout: number = 100
  ): Promise<Response> => {
    const controller = new AbortController()
    const timeout = setTimeout(() => {
      console.log('timeout')
      controller.abort()
    }, requestTimeout)

    let options = {
      method: 'POST',
      body: JSON.stringify({ data: userCsr }),
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal
    }
    if (this.tor) {
      options = Object.assign({
        agent: this.socksProxyAgent
      }, options)
    }

    try {
      const start = new Date()
      console.log('a')
      await new Promise((resolve) => {
        setTimeout(resolve, 5000)
      })
      console.log('b')
      const response = await fetch(`${serviceAddress}/register`, options)
      const end = new Date()
      const fetchTime = (end.getTime() - start.getTime()) / 1000
      log(`Fetched ${serviceAddress}, time: ${fetchTime}`)
      return response
    } catch (e) {
      log.error(e)
      throw e
    } finally {
      clearTimeout(timeout)
    }
  }`

Result with

`  waggle:socket Registering user certificate (98950D47C23629B30B376F2C1F0DE902) on http://yn2owgfadan6hhnsu77rrql4s3vou76zvvave5n7gazencr733hdbyid.onion +5s
a
timeout
b
  waggle:conn:err AbortError: The user aborted a request.
  waggle:conn:err     at abort (/Users/apple/Documents/monorepo/packages/waggle/node_modules/node-fetch/lib/index.js:1418:16)
  waggle:conn:err     at /Users/apple/Documents/monorepo/packages/waggle/node_modules/node-fetch/lib/index.js:1428:4
  waggle:conn:err     at new Promise (<anonymous>)
  waggle:conn:err     at fetch (/Users/apple/Documents/monorepo/packages/waggle/node_modules/node-fetch/lib/index.js:1407:9)
  waggle:conn:err     at ConnectionsManager.<anonymous> (/Users/apple/Documents/monorepo/packages/waggle/lib/libp2p/connectionsManager.js:203:65)
  waggle:conn:err     at Generator.next (<anonymous>)
  waggle:conn:err     at fulfilled (/Users/apple/Documents/monorepo/packages/waggle/lib/libp2p/connectionsManager.js:24:58) +5s`

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.4

Fixed
