### ISSUE TITLE
Channels should display in a consistent order

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#239]
We should display channels in a consistent order in the left sidebar. 

General channel should always be first, then alphabetical order. 

For channels with the same name we can sort by some other identifier like orbitdb sequence info, perhaps? 

Creating another channel named "general" should not put it at the top of the list or replace the existing general channel. 

Sorting by orbitdb sequence works too, if that is easier.

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

Sorting channels with unique names is working (as you can see on the screen).

Creating channels with the same name is not possible at the moment (including "general").

![Screenshot 2022-03-16 at 12 20 04](https://user-images.githubusercontent.com/68909168/158578747-d68b5575-aa39-4aa4-bb23-1d3f8d124e0d.png)
