### ISSUE TITLE
user cannot create a channel with only whitespaces as the name, but user does not receive a clear error message

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#240]

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/issues/211

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/247

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

I consider this a clear message.

![Screenshot 2022-03-16 at 13 49 03](https://user-images.githubusercontent.com/68909168/158593385-ad8bd70a-2572-47fd-a49b-4c865d88beb6.png)
