### ISSUE TITLE
Long single words in a message can break UX

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#241]
Steps to reproduce:

Enter a message with a long word e.g. 
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

expected: fine, it displays, and wraps. 

actual: it messes up the UX. 

we should have CSS/chromatic tests to catch this.

let's do this right and try to cover all the other cases too. unicode text, special characters, long words, super long messages, etc.

**Comment by kingalg** [comment]
Version: 0.3.0-alpha.8

I've try to break it in several ways including among others:
- typing one very long word,
- pasting very long word,
- typing and sending long messages from two accounts at the same time,
- repeating points mentioned above with numbers and special characters.

It all seams to be working fine.
