### ISSUE TITLE
Minimum window size breaks the UI

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#244]
![image](https://user-images.githubusercontent.com/213678/153657906-21922c2d-48a3-421a-8cea-ce7fec0c2b2b.png)

this is on debian buster, running on chromebook

**Comment by kingalg** [comment]
Version 0.3.0-alpha.8 - fixed
![Screenshot 2022-03-04 at 13 24 12](https://user-images.githubusercontent.com/68909168/156762971-ac06157a-312a-4f97-9438-ba0bceb4da9e.png)
