### ISSUE TITLE
Sound plays "twice" on mac and windows (OS default sound + our custom sound) 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#271]
QA says:

"About sounds... We have 3 possible notification sounds and it's working just fine on linux. Mac and Windows have their own predetermined notification sounds and for Quiet we get combination of their sound and our sound. I'm checking in the settings if it's something that I can change in the system but to be honest I never had this problem with any program so it's a first time I'm checking this."

I believe we encountered this before and had to use some electron thing on the notification to disable default OS sounds on Mac and Windows.

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.5

Now only our custom sound are played. All three are working. Turning off notification sound is working as well.
