### ISSUE TITLE
On restart, user should be scrolled to the latest messages in the channel (they aren't)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#272]
problem: right now if you restart the app you might not see that there are new messages in a channel. 

Steps: send lots of messages, restart

Expected: you are scrolled to the latest messages

Actual (according to QA): you are scrolled to the first messages in that channel

If there's some subtlety here I'm missing, lmk!

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.4

Fixed.
