### ISSUE TITLE
Windows - pass logo to notifications and correct the app name - blocked by 404

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#280]
Window 10 notifications don't contain logo and the title is displayed as "electron.app.Quiet":

![image](https://user-images.githubusercontent.com/6099829/155731275-aa92e69a-d1a9-4cee-9a51-b92c641a01ab.png)

(logo should be visible on mac too...)

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.5

Logo and correct name are there.

![Screenshot 2022-04-06 at 10 13 27](https://user-images.githubusercontent.com/68909168/161928042-04640c3a-f55d-4693-be27-5001ff07e67c.png)
