### ISSUE TITLE
Window not draggable on join community screen on mac

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#282]
steps to reproduce:

1. start on mac
2. try to drag window

expected: can drag by clicking in top area

actual: can't drag

(is there any way to have a test for this? this is a regression)

**Comment by siepra** [comment]
We use electron's frameless window ("A frameless window is a window that has no [chrome](https://developer.mozilla.org/en-US/docs/Glossary/Chrome), the parts of the window, like toolbars, that are not a part of the web page.").

Following the official electron documentation: "By default, the frameless window is non-draggable. Apps need to specify -webkit-app-region: drag in CSS to tell Electron which regions are draggable (like the OS's standard titlebar)".

We had few components specifying WebkitAppRegion which was causing dragging feature to be random.

My proposition is to overlap the root component with invisible, draggable wrapper with the height of 25px and top position 0 instead.

**Comment by siepra** [comment]
Related PR
https://github.com/ZbayApp/monorepo/pull/332

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.1

It's dragable now on Mac.
