### ISSUE TITLE
Notification should preface channel name with # - blocked by 404

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#287]

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.5

It's working.

![Screenshot 2022-04-06 at 09 54 31](https://user-images.githubusercontent.com/68909168/161924453-6b741dfa-3e70-44a0-8f28-7843e8f8ea9c.png)
![Screenshot 2022-04-06 at 10 10 43](https://user-images.githubusercontent.com/68909168/161927511-3b98a477-7883-4017-be39-4436a15f2c6c.png)
