### ISSUE TITLE
Message I sent yesterday shows up under "Today" 1 day later

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#304]
steps to reproduce:
1. send message
2. wait a day

expected: message no longer appears as "today". "today" title changes to date.

actual: it appears under "today"

![image](https://user-images.githubusercontent.com/213678/156807686-9d874435-c6b6-4c1d-a001-3a30eb5cef96.png)

**Comment by siepra** [comment]
Related PR
https://github.com/ZbayApp/monorepo/pull/329

**Comment by kingalg** [comment]
@holmesworcester @siepra - it still appears under "today". Something change with the decision or this is not resolved?

![Screenshot 2022-03-30 at 09 51 57](https://user-images.githubusercontent.com/68909168/160780239-8c815fa4-9f93-47d5-8426-9e7977b0180d.png)

**Comment by holmesworcester** [comment]
Not resolved I think

**Comment by kingalg** [comment]
Never mind, it's ok, I understood the task wrongly.
![Screenshot 2022-03-31 at 10 54 15](https://user-images.githubusercontent.com/68909168/161016937-469e08cd-8d93-4282-9192-0610b7407518.png)
