### ISSUE TITLE
Too many individual notifications display for old messages when you reopen the app.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#307]
Right now if you have notifications turned on, reopening the app after having been absent for a bit shows a huge number of notifications (one for each new message)

Worse, this happens for users the first time they start the app!

Here's the approach we want to take, but if you can see problems please push back and propose something else:

1. App remembers the time it came online, the first time the user runs the app, but also each time the user reopens the app.
2. "Time it came online" can be the moment the main app screen with channel list and message view is visible to the user.
3. App does not notify for messages sent with timestamps before the time it came online (it trusts the timestamps, which can be forged, but this seems tractable with future changes) 
4. Channels with unread messages still appear highlighted until the user clicks on the channel.

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.5

App behaves as described but it's a little bit slow, so I'm going to close this but have an eye on everything that happens after reopening.
