### ISSUE TITLE
User should be able to receive notifications according to their preferences

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#31]
Right now notification settings are present but don't appear to work. We should ensure that they work, according to the preferences.

**Comment by kingalg** [comment]
They are mostly working. Below part doesnt work yet as we don't have mentiones, keywords and direct messages implemented.

![image](https://user-images.githubusercontent.com/68909168/155724062-bc93dae2-6d52-4ea0-862c-785b88c86425.png)
