### ISSUE TITLE
Fix registrar error handling in waggle

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#311]
Registrar uses emitValidationError and emitServerError to send username registration failure info down to nectar. Error codes in those two methods are fixed (401, 500).
We need to extract unique error codes (eg for 404 response) and pass the information about the exact error both to nectar and waggle's request retry function (also there's a need to add some interval for retrying)

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/314

**Comment by siepra** [comment]
QA:
Check if registrar errors are working correctly (username taken, request failure etc...)

**Comment by kingalg** [comment]
Looks fine. The only thing that I don't like in errors is how error is showing when user switch between join and create a community, but that will be handled by different issue.
