### ISSUE TITLE
Remove minimum character length for names (username, community, channel) to allow 1 character names.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#319]

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.1

Status: I confirm that it's working on all systems for channels, communities and usernames

![Screenshot 2022-03-29 at 15 10 34](https://user-images.githubusercontent.com/68909168/160618634-9f9c8d7b-7a7a-4d68-8b7f-c3ef026823a8.png)
