### ISSUE TITLE
Change name to Quiet

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#32]
Names to change:

- The repo name should be Quiet. 
- The name in the code
- What the app runs as.

Separate issue created for the logo, so no need to worry about this.

**Comment by EmiM** [comment]
What about the organization name on github?

**Comment by kingalg** [comment]
I was looking for zbay name in every place I could think about and looks like it's all gone (I will still have an eye on this). I suppose that the company is stil Zbay LLC, so this part is ok @holmesworcester ?
![Screenshot 2022-03-04 at 11 54 02](https://user-images.githubusercontent.com/68909168/156750521-a7e19786-f2a8-4e1f-98cf-73da867fe00d.png)

**Comment by holmesworcester** [comment]
Where is that?

**Comment by kingalg** [comment]
It's in Quiet info that you get after installing the program.

And @vinkabuki - @EmiM already asked in this task so you've probably discussed it but what about "zbay" in github?

![Screenshot 2022-03-04 at 14 16 08](https://user-images.githubusercontent.com/68909168/156770076-cd87278d-d095-4aff-a505-39a78dc1daae.png)

**Comment by kingalg** [comment]
@holmesworcester can I close this or we are still working on the case that I mentioned above and on a name in github?

**Comment by holmesworcester** [comment]
@kingalg the company name is still Zbay LLC so that's fine. Github we can do separately from this ticket.
