### ISSUE TITLE
Manual QA on an m1 Mac

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#33]
Devs should ensure that it works and that there aren't any performance problems

We should make sure it's very fast and comfortable.

It's likely that it will be slow until we fix issues in #68. But if it works great out of the box that's great! 

If not, let's take some of the steps in #68 to make sure it works reasonably well. 

(Rumblefish is buying an M1 to test in the office)

**Comment by EmiM** [comment]
Blocked by https://github.com/ZbayApp/monorepo/issues/45

**Comment by siepra** [comment]
Applications connects to other peers a little bit slower than it does with other processors (it takes a little bit longer to register certificates) but replicating data doesn't seem to take longer than regular
