### ISSUE TITLE
Community name should display

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#34]
The community name should display in the top left where we currently display the user name. 

We should validate community name length so that it displays correctly, or truncate it with CSS in a clear way (e.g. with ellipses like "longcommunityna...") 

The first letter of the community name should be forced to be capitalized. (That's what we're doing in the design, at least.) 

Here's the design: 

https://www.figma.com/file/qwkBkjAbewMd4Ze6UW1rk3/Communities?node-id=266%3A695

(Ignore the left sidebar for now, since we don't have multiple communities yet) 

This name area should never be empty, so on first run we should show the loading spinner until we have a community name.

Only the admin should be able to add a community name to orbitdb / waggle, and they should not be able to change it, or we should ignore changes (e.g. use log and just look at first entry.)

**Comment by vinkabuki** [comment]
https://github.com/ZbayApp/monorepo/pull/151

**Comment by kingalg** [comment]
The first letter of the community name should be forced to be capitalized. (That's what we're doing in the design, at least.) - this point is not done correctly (as you can see on the screen below)

![image](https://user-images.githubusercontent.com/68909168/155729563-542787ce-e84b-4ee0-b061-5d5180d3459f.png)
