### ISSUE TITLE
Write script to add additional messages to a community to see when scaling issues emerge

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#347]
Goals: We're dogfooding the app now, but it would be helpful to learn from dogfooding what level of new message traffic (or existing message history) creates scaling problems.

There are two pieces to this:

1. Filling the community we're dogfooding in with bogus messages so that we can see when using the app becomes difficult. (Testing the entire app in a real-world scenario.)

2. Figuring out what the limits of the stack we're using are, independent of our own app, and providing failing tests to OrbitDB (or IPFS or maybe Tor teams) that show when the stack breaks down. We want to know when replication of new messages gets too slow, or when the number of past messages grinds the system to a halt. Waggle tests probably make the most sense for this, since they isolate the part of the stack we don't control, but in a way that mirrors our use case.

Does this make sense?

Questions:

1. How much message history in a channel makes the channel slow?
2. How much message history in community (a spam channel) makes app slow?
3. What rate of messages in a moment makes app slow in that moment? (in a community, e.g. in spam channel)
4. How many users online make app slow?
5. How many total users (not online) make app slow?

**Comment by holmesworcester** [comment]
@EmiM we already have a tangible issue to focus on for what the actual app is like (#374) and it's related to our own frontend most likely, so I propose we focus on that specific issue for "real world performance" and then focus on waggle limits to answer the questions about "theoretical limits of stack". Does that make sense? 

I think it probably makes sense to look at the slowness in #374 first (or whenever you're at a stopping point) and then come back to these investigations, focused on waggle or nectar/waggle.

**Comment by EmiM** [comment]
I agree. The script for realistically spamming the channel is basically done, I just have to adjust the "realistic" part (breaks between each message etc.) because right now is very bot-like:

![image](https://user-images.githubusercontent.com/6099829/159347039-168e04af-496f-4f04-b3f4-2761805fc1b5.png)

**Comment by holmesworcester** [comment]
@EmiM awesome! and it's probably totally okay for it to be bot-like, as long as we think it will cause similar problems compared to real usage.

**Comment by holmesworcester** [comment]
Let's consider these done now and use with them again when we feel like we've addressed syncing performance.  A lot of the above questions about stack performance have been covered by new issues: #384 #389 #390 #391
