### ISSUE TITLE
Scroll position in one channel is affected by scrolling in another channel

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#366]
Steps to reproduce:

1. Scroll to bottom in general
2. Switch to another channel and scroll up
3. Switch back to general

Expected: scroll is at the bottom and you can see new messages

Actual: scroll is in the middle and you can't see new messages

**Comment by Dinek007** [comment]
https://github.com/ZbayApp/monorepo/pull/423

**Comment by holmesworcester** [comment]
I think saving scroll position might be better but I'd want to review other apps first. As long as the weird behavior described in this issue is fixed I think we're good.

**Comment by kingalg** [comment]
So I'm closing this issue as mentioned bug is fixed. The rest can be implemented in the future if needed.
