### ISSUE TITLE
Improve UX on invite screen

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#37]
The create link/copy to clipboard button for invite link is confusing. You click on the button to generate an invite link, but then the button changes when you're already hovering over it, so the "copy to clipboard" button is greyed out and doesn't seem readable/clickable.

A quick fix is for the invite link to appear as soon as you switch to this screen, and show a spinner until it appears. That way there's no need to click.

Let's try this.

A better fix would be to get a better design for this section and build it right the first time. If necessary I'll work on this better design with our designer. 

(The current design is here, but has issues: https://www.figma.com/file/qwkBkjAbewMd4Ze6UW1rk3/Communities?node-id=266%3A6. "Invite a friend" is used interchangeably for "Add members" and it's not specified what happens when you click "Invite a friend")

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/149

**Comment by kingalg** [comment]
For now it looks ok.
version: 0.3.3-alpha.7
