### ISSUE TITLE
Can't send messages after joining a community with a lot of existing messages (slowdown?)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#374]
Steps to reproduce:

1. Join existing Quiet team community
2. Try to send a message

Expected: message is sent, and appears

Actual: nothing happens. No message appears.  (for many seconds)

same thing happens when syncing lots of messages after rejoining, but not as extreme. 

Work on this issue should begin with writing a failing e2e test (#379).

Then we have two things we can try, which we can do in parallel: 

1. move to profiling to see what's slowing things down. https://www.electronjs.org/docs/latest/tutorial/performance#measure-measure-measure

2. Don't do anything that blocks the renderer or main process. https://www.electronjs.org/docs/latest/tutorial/performance#checklist-performance-recommendations

3. Another thing is that when syncing orbitdb will be slow to display our message. So we have to put the message into nectar immediately when you send it. A bonus would be to grey it out until we think it's been displayed to other users. But that's just a bonus and I'm not sure we can know that.

4. Another possibility is that this is the websockets queue. 

5. "It may be as easy as throttling events emitted by waggle for nectar" -- marek

6. If OrbitDB itself is blocked on sending out new transactions because it's syncing, that's a problem. Somebody should be able to join a community, say hi right away, and have that message received, at least within 1 or 2 seconds if not instantly. We should ensure that orbitdb is not a blocker here and if it is we should make an issue for orbitdb. 

If we can confirm that orbitdb is the bottleneck we should attempt #3 first and see if that resolves the problem. 

It seems best for two or more people to work on this.

**Comment by Dinek007** [comment]
https://github.com/ZbayApp/monorepo/pull/387, fixes reliability not performance

**Comment by holmesworcester** [comment]
I think we should do #379 first so that we have a failing performance test, and then fix the performance piece.

**Comment by holmesworcester** [comment]
We can work on part of this now, even before we have the performance test.

Let's move waggle to its own process so that it doesn't block main or renderer. 

See conversation with marek in slack: https://zbay.slack.com/archives/G01EHE6JHCM/p1648218503901089

**Comment by holmesworcester** [comment]
We've tried moving waggle to its own process, and we've tried showing some provisional (greyed out) message on send, but neither of these steps eliminates the lag. 

It seems like we should add some logging or using profiling tools to see where the lag is and why we run into this problem.

**Comment by kingalg** [comment]
It's resolved in v 0.5.0-alpha.0 - checked on all supported systems, also in one old and slow computer.
