### ISSUE TITLE
New incoming messages hidden on chromebook due to failure to scroll down.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#382]
let's return to this once lazy loading is fixed in #386

**Comment by holmesworcester** [comment]
If this bug turns out to be very specific to ChromeOS let's deprioritize it.

If it's a performance related issue then this is the right priority.

**Comment by siepra** [comment]
Related to https://github.com/ZbayApp/monorepo/issues/386, fix will be included in https://github.com/ZbayApp/monorepo/pull/401

**Comment by holmesworcester** [comment]
This isn't working in 1.4.1-alpha.5 for me. I still have to scroll down manually to see new messages.

**Comment by siepra** [comment]
Duplicate of https://github.com/ZbayApp/monorepo/issues/231
