### ISSUE TITLE
Switching channels is sometimes slow, especially with many new incoming messages

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#385]
steps to reproduce:

1. send a lot of messages using the spam bot
2. try to switch channels

expected: it's still fast
actual: it's really slow

hypothesis: it's slow because we put all messages in the same redux store

another hypothesis: it's slow because replicating generally slows down the app. 

It seems possible that #374 and #386 will fix this so let's do those first.

We should write an automated performance test based on #379 to make sure switching channels stays snappy.

**Comment by holmesworcester** [comment]
We think this has been addressed but @kingalg and team should verify that switching channels is fast with lots of messages.

**Comment by kingalg** [comment]
It's working rather fast for me in version 0.4.1-alpha.5. I've spammed many channels with a lot of messages and switching between them on Windows and MacOS was fast and flawless.
