### ISSUE TITLE
lazy loading is broken

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#386]
steps:

1. load general channel

expected: not all messages are visible, only recent ones, because loading is lazy. 

actual: all messages are visible. loading is not lazy.

we should really try to make a regression test for this. 

Unblocks #383 and #385 and #382 so move those to top of sprint when this is done.

**Comment by siepra** [comment]
Related PR Related to https://github.com/ZbayApp/monorepo/issues/386, fix will be included in https://github.com/ZbayApp/monorepo/pull/401

**Comment by siepra** [comment]
Related to #419

**Comment by kingalg** [comment]
Working as expected in 0.4.6-alpha.0.
