### ISSUE TITLE
Registration fails, doesn't retry

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#393]
Steps to reproduce:

1. Create community
2. Join community from another client

Expected: username registration works. 

Actual: it often fails. 

I think this is due to timeout. Sometimes on the registrar side I see nothing happen. Sometimes I see it receive the request, but it still fails on the new user side.  

If there are any problems connecting with Tor, we retry. We try multiple times in parallel so that if one connection attempt takes a long time, we start other attempts, but keep trying the initial attempt so we aren't always timing out too early. 

There should be a nectar/waggle test where we try to register with an unavailable registrar or slow response, and keep trying.

There should be an e2e test for this too, since I'm pretty sure the reason for the regression was that we did a refactor and didn't have an e2e test. 

If we want to expose the retry attempts to the user or let the user initiate a retry that's good too, but we should keep retrying automatically also. 

NOTE: if we can't reproduce this, just take registrar down or make it respond artificially slowly and ensure things still work.

**Comment by vinkabuki** [comment]
Actually we do retry etc, it's just the frontend misrepresenting what's going on

**Comment by kingalg** [comment]
Version: 0.4.6-alpha.0

Fixed

Tested:
1. Install new Quiet
2. Try joining to a non-existing community (I used: msxyndgstn7nilc2lch5dimxmvug772bedkstn333lax5uap7umiyxqd)
3. Between 35 s - 10 min you should get an error "Connection to registrar failed".
4. Steps 2-3 can be retried by repeatedly trying using button "Register" and result should be always error message.

<img width="642" alt="Screenshot 2022-04-22 at 10 41 22" src="https://user-images.githubusercontent.com/68909168/164652562-b6229119-5f40-43d2-8199-91aa1ea808a1.png">
