### ISSUE TITLE
Just got notification "new message from unknown user" which should not be possible

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#394]
Steps to reproduce (maybe!):

1. Run two quiet instances
2. Join a community with a lot of messages
3. Send messages back and forth between client that is has already joined and client that has just joined. 

Expected: notification should never say "unknown user" 

Actual: notification says "new message from unknown user in general"

The weird thing here is that the messages in the UI had already displayed as being from a known user. So it must have gotten queued before the user was known.

**Comment by Dinek007** [comment]
https://github.com/ZbayApp/monorepo/pull/406

**Comment by kingalg** [comment]
So far it looks like in 0.4.6-alpha.0 it's working.
