### ISSUE TITLE
No navbar in new node/electron build on windows

### ISSUE THREAD

**Issue by vinkabuki** [ZbayApp/monorepo#416]

**Comment by holmesworcester** [comment]
Options: 

1. Show the default navbar on windows, as we do on linux.
2. Add custom close buttons, as we do on Mac.

If there's a library or template for the latter in a way that's similar to other windows apps, let's do it (#2 above). It'd be nice to have the left sidebar color run top to bottom as it does on Mac. This isn't super important though, obviously.

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/454

**Comment by kingalg** [comment]
Version: 0.4.6-alpha.0

1. Show the default navbar on windows, as we do on linux. - fixed
2. Add custom close buttons, as we do on Mac. - to be done in the future (agreed with Holmes)

![image (1)](https://user-images.githubusercontent.com/68909168/164649090-2e06e803-5cca-4198-91c2-755e0e97e17e.png)
