### ISSUE TITLE
Lazy loading doesn't work during the first app run

### ISSUE THREAD

**Issue by siepra** [ZbayApp/monorepo#419]
It regenerates after restarting the app

**Comment by holmesworcester** [comment]
I don't see this behavior in my version. I see it work under some circumstances but not for all channels.

**Comment by holmesworcester** [comment]
This might be related to #366 where being scrolled up in one channel can scroll you up in another channel too.

**Comment by Dinek007** [comment]
https://github.com/ZbayApp/monorepo/pull/423

**Comment by kingalg** [comment]
Working as expected in version 0.4.6-alpha.0.
