### ISSUE TITLE
Loading indicator doesn't display in Quiet alpha 4

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#424]
Steps to reproduce:

1. Start a latest version of Quiet

Expected: user sees "Starting Quiet" or some type of indication of what is happening, and a loading spinner.

Actual: user sees white screen. 

Verify that this is working correctly with an e2e test.

Bonus: loading spinner should display instantly on startup with zero or very minimal white screen once window opens.

**Comment by kingalg** [comment]
It's displayed on all systems in 0.4.6-alpha.0
