### ISSUE TITLE
Move waggle to a separate process so it doesn't block main and render, then look into websocket as bottleneck

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#428]
See #374

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/439 <- this is the change me and Bartek was testing on (forked waggle)

I created community with 3 channels with 1000, 1000 and 500 messages.
I tested two scenarios:
* using the app while spam-bot messages were arriving
* being the new user that joins to the old community with > 2500 messages

Unfortunately I didn't see any improvement in any case. 
Joining user's messages were "disappearing" and sent with huge delay.
