### ISSUE TITLE
Sent messages should appear *immediately* in grey even if they are not sent

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#429]
Problem: user sends a message and it disappears from their point of view, even though others receive it. 

Fix: when user sends message, it should display immediately in grey, even if it has not been saved in orbitdb or shared etc. Then when we know it has been saved in orbitdb, its status should change (internally) to sent and it should appear as every other message.  

Related to #374

**Comment by kingalg** [comment]
It's grey at the very beginning in v 0.5.0-alpha.0

How to test:
1. With a freshly installed Quiet join community that has thousands of messages (in my case it was our team community). 
2. Immediately try to send a new message.
3. For a moment it should appear in grey (the older computer is the easier it's to see it).
