### ISSUE TITLE
Strip invitation address from whitespaces as user types/pastes it to a field

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/monorepo#44]
We should strip invitation address from whitespaces when user pastes/types it into a field. That's because it's common to copy a whitespace by mistake and then be frustrated because the app is saying that the address is not correct (even if it appears to be correct).

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/192

**Comment by kingalg** [comment]
Version 0.4.0-alpha.3

Fixed.
