### ISSUE TITLE
Settings (e.g. for notifications) are forgotten on restart

### ISSUE THREAD

**Issue by vinkabuki** [ZbayApp/monorepo#447]
steps to reproduce:

1. change the settings
2. restart app

expected: settings still present
actual: settings lost

**Comment by holmesworcester** [comment]
@vinkabuki what's the deal with this one?

**Comment by vinkabuki** [comment]
@holmes When you open the app and you change your notifications preferences e.g sound, or turn them off completely, after restarting app they are reset to default values and you have to change them every time you restart app.

**Comment by kingalg** [comment]
Resolved in v 0.5.0-alpha.0.
