### ISSUE TITLE
Quiet stuck on "fetching data" if registration process is interrupted

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/monorepo#482]
Quiet stuck on "fetching data" if registration process is interrupted in v 0.5.0-alpha.0

How to reproduce:
1. Prepare new quiet and register or join community.
2. Wait until user registration screen appear - turn off Quiet.
3. Reopen application.
Expected behaviour: user registration screen appear and user can continue registration.
What is happening: Quiet is stuck on "Fetching data" screen.

Emilia reproduced it also by trying to register when registrar is off and closing an app.

**Comment by holmesworcester** [comment]
Let's make sure there's an e2e test for this!

**Comment by kingalg** [comment]
Fixed.
