### ISSUE TITLE
Adding trailing space in invite code blocks joining community

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#492]
steps to reproduce;

1. start fresh quiet
2. paste invite code
3. type a space at the end
4. OR copy invite code with trailing space

expected: leading/trailing space ignored

actual: the space does not appear in the field, but its presence causes input to be invalid and user gets an error to check the code.

**Comment by siepra** [comment]
Related PR https://github.com/ZbayApp/monorepo/pull/494

**Comment by kingalg** [comment]
I successfully joined community on two different systems with adding space at the end of an invite code. This issue is fixed.
