### ISSUE TITLE
Pasting rich text into message entry field causes layout chaos

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#50]
Steps to reproduce:

(on mac)

1. Copy rich text from Chrome or Safari (I saw this on Mac) like text from a webpage including formatting and images.
2. Paste into text entry field

Expected: app layout does not get messed up.

Actual: rich text gets pasted into the field and all hell breaks loose with the app layout. 

![image](https://user-images.githubusercontent.com/213678/145577847-78ab8ed2-d838-4d50-bf1f-db8419e952f3.png)

Note: we don't have to prevent rich text from being pasted into this field. It's just that the field shouldn't resize in a way that messes up the app layout.

**Comment by kingalg** [comment]
In vestion 0.3.0-alpha.7 there is no rich text (no colours, bold, etc) but also no enters. I'm not sure if enters should be there or not (@Dinek007 can't say for sure as well) so could you confirm @holmesworcester ?

**Comment by holmesworcester** [comment]
That's fine, yes
