### ISSUE TITLE
Zbay crashes on every restart following initial internal restart for entropy.

### ISSUE THREAD

**Issue by tallship** [ZbayApp/monorepo#57]
The instructions within the application said that it should take a bit less than an hour, and to more securely anchor the installation I should click to restart it and then everything should be optimum.

OS = Win 10/64
Zbay version (unable to check, but installed about two hours ago).

I installed Zbay. I take my time reading and looking over, and noting that it didn't say 'beta' anywhere decided to set it up and give it a try.

I couldn't find anywhere to set it to use TOR by default for private messages, and read where it suggested closing and relaunching to achieve I guess, maximum entropy?

Anyway, when I clicked to let it close and reopen I got errors which it wanted to send to the dev team, and then locked me out. It won't successfully launch at  all now, and keeps coming up with the error which I grant access for it to report.

I did not fund it, although I was ready to right after that reboot. At this point it looks like I'll need to uninstall and reinstall but nowhere did I see a place to restore using my private paper recovery phrases.

**Comment by vinkabuki** [comment]
Closing.
