### ISSUE TITLE
Messages won't sync after long sleep

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/monorepo#84]
Steps to reproduce:

1. Join a community with two macs
2. Confirm messaging and sync works.
3. Close both macs for 1 or perhaps 2 days (time closed seems to matter) and then open both and try sending messages.

Expected: apps can still send messages to each other.

Actual: they cannot. restart is required.

The tricky thing about this is covering this case with a test, which we should do, because it's given us problems a bunch of times in the past. How do we cover it with a test? How do we simulate "suspend" (..."for two days" ugh!!). Perhaps there's a Tor state we can simulate, if it's a Tor problem.

Also, are there any system level tests we should have on Mac/Windows/Linux?

* All the variations of sleep, suspend, power save
* Wifi on off
* Wifi network change / IP address change
* Anything else?

**Comment by kingalg** [comment]
I've waited 2 days (weekend) and messages synced.
Version: 0.3.0-aplha.7
